app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /
    schemes:  [%httpProtocol%]

logout:
    path: /logout

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /

coresphere_console:
    resource: .
    type: extra