app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /
    schemes:  [%httpProtocol%]

logout:
    path: /logout

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"