security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: root
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: managerLogin
                check_path: managerLogin
            logout:
                path:   /logout
                target: /


    access_control:
        - { path: ^/managerLogin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manager*, roles: ROLE_ADMIN }