# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # Services
    # ------------------------------------------------------------------------------------------------------------------
    app.service.manual:
        class: AppBundle\Service\ManualService
        arguments: ['@doctrine.orm.entity_manager']

    app.service.download:
        class: AppBundle\Service\DownloadService
        arguments: ['@doctrine.orm.entity_manager']

    app.service.report:
        class: AppBundle\Service\ReportService
        arguments: ['@doctrine.orm.entity_manager']

    app.service.entitytools:
        class: AppBundle\Service\EntityToolsService
        arguments: ['@doctrine.orm.entity_manager']

    app.service.application:
        class: AppBundle\Service\ApplicationService
        arguments: ['%kernel.root_dir%']

    # Listener
    # ------------------------------------------------------------------------------------------------------------------
    app.listener.maintenance:
        class: AppBundle\Listener\MaintenanceListener
        arguments:
            container: "@service_container"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # Twig
    # ------------------------------------------------------------------------------------------------------------------
    twig.extension.text:
         class: Twig_Extensions_Extension_Text
         tags:
             - { name: twig.extension }

    twig.extension.stringloader:
           class: Twig_Extension_StringLoader
           tags:
               - { name: twig.extension }


    # Doctrine GEDMO extensions
    # ------------------------------------------------------------------------------------------------------------------
    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

