# app/config/services.yml
services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: false
        tags: ['controller.service_arguments']


    # Services
    # ------------------------------------------------------------------------------------------------------------------
    AppBundle\Service\ManualService: ~
    AppBundle\Service\DownloadService: ~
    AppBundle\Service\ReportService: ~
    AppBundle\Service\EntityToolsService: ~
    AppBundle\Service\ArticleService: ~
    AppBundle\Service\ApplicationService:
        arguments:
            $kernelPath: '%kernel.root_dir%'

    # Listener
    # ------------------------------------------------------------------------------------------------------------------
    AppBundle\Listener\MaintenanceListener:
        arguments:
            $maintenance: '%maintenance%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    app.sitemap.subscriber:
          class:     AppBundle\Listener\SitemapSubscriber
          arguments:
              - "@router"
              - "@doctrine.orm.entity_manager"
          tags:
              - { name: "kernel.event_subscriber", priority: 100 }

    # Twig
    # ------------------------------------------------------------------------------------------------------------------
    twig.extension.text:
         class: Twig_Extensions_Extension_Text
         tags:
             - { name: twig.extension }

    twig.extension.stringloader:
           class: Twig_Extension_StringLoader
           tags:
               - { name: twig.extension }


    # Doctrine GEDMO extensions
    # ------------------------------------------------------------------------------------------------------------------
    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

