vich_uploader:
    db_driver: orm

    mappings:
        manual_image:
            uri_prefix:         /images/manual
            upload_destination: '%kernel.root_dir%/../%upload_dir%/images/manual'
            namer: vich_uploader.namer_origname

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

        download_image:
            uri_prefix:         /images/download
            upload_destination: '%kernel.root_dir%/../%upload_dir%/images/download'
            namer: vich_uploader.namer_origname

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

        article_image:
            uri_prefix:         /images/article
            upload_destination: '%kernel.root_dir%/../%upload_dir%/images/article'
            namer: vich_uploader.namer_origname

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

        download_file:
            uri_prefix:         /downloads
            upload_destination: '%kernel.root_dir%/../%upload_dir%/downloads'
            namer: vich_uploader.namer_origname

            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true